# Generated by Django 4.2.4 on 2023-08-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_app', '0002_remove_project_contributors_alter_project_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(related_name='contributed_projects', to='softdesk_app.customuser'),
        ),
    ]
