# Generated by Django 4.2.4 on 2023-08-17 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('softdesk_app', '0003_project_contributors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributors',
            new_name='contributor_users',
        ),
    ]
